EAM-715
cern-eam/eam-components pull request #52
Opened 2020-10-01 14:25 UTC by BoykoBorisov

2020-10-02 07:42 UTC, pedroamarocern reviewed
Looks good, just a state mutation issue.

2020-10-02 07:42 UTC, pedroamarocern commented on src/ui/components/checklists/ChecklistSignature.js
> +          qualification: this.props.signature.responsibilityDescription,
Inconsistent usage of `props` and `this.props`.

2020-10-02 07:42 UTC, pedroamarocern commented on src/ui/components/checklists/ChecklistSignature.js
> +export default class ChecklistSignature extends Component{
Nitpick: `export default class ChecklistSignature extends Component{` => `export default class ChecklistSignature extends Component {`

2020-10-02 07:42 UTC, pedroamarocern commented on src/ui/components/checklists/ChecklistSignature.js
> +    openDialogue = () =>{
`openDialogue = () =>{` => `openDialogue = () => {` (as below)

2020-10-02 07:42 UTC, pedroamarocern commented on src/ui/components/checklists/ChecklistSignature.js
> +       var signature = {workOrderCode: this.props.workOrderCode,
Why is `var signature` used here and not `const signature`?

2020-10-02 07:42 UTC, pedroamarocern commented on src/ui/components/checklists/ChecklistSignature.js
> +        });
Optional, more concise: can use `.finally(this.closeDialogue)` instead of specifying it twice.

2020-10-02 07:42 UTC, pedroamarocern commented on src/ui/components/checklists/ChecklistSignature.js
> +    }
Why not simply call `this.closeDialogue();`?

2020-10-02 07:42 UTC, pedroamarocern commented on src/ui/components/checklists/ChecklistSignature.js
> +    }
This can be simplified: https://ultimatecourses.com/blog/deprecating-the-switch-statement-for-object-literals

2020-10-02 07:42 UTC, pedroamarocern commented on src/ui/components/checklists/ChecklistSignature.js
> +            label = this.signatureTypeSwitch(this.props.signature.type);
Would a ternary operator simplify the logic here?

2020-10-02 07:42 UTC, pedroamarocern commented on src/ui/components/checklists/ChecklistSignature.js
> +              <label style={{fontSize: '0.825rem', color: 'rgb(20, 88, 134)'}}>{label}</label>
Good use of `rem` for font size!

2020-10-02 07:42 UTC, pedroamarocern commented on src/ui/components/checklists/ChecklistSignature.js
> +                    <Grid item xs={2} md={2} lg={2}>
Nitpick: unnecessary spaces at end of line.

2020-10-02 07:42 UTC, pedroamarocern commented on src/ui/components/checklists/Checklists.js
> +            signaturesCollapsed: new Map()
Can also likely use an Object: `signaturesCollapsed: {}`.

2020-10-02 07:42 UTC, pedroamarocern commented on src/ui/components/checklists/Checklists.js
> +        this.setState(this.state.signaturesCollapsed.set(activity, !this.state.signaturesCollapsed.get(activity)));
Do note that this mutates the original this.state and returns the same one.

Consider the following:
```js
const a = new Map();
const b = a.set('key', 'value');
console.log(a === b); // true
```

2020-10-02 07:42 UTC, pedroamarocern commented on src/ui/components/checklists/Checklists.js
> +          return;
Generally when performing short ifs without brackets we put the statement that will be executed on the same line (`if (!activity.signatures) return;` or simply use brackets:

```js
if (activity.signatures) {
    return;
}
```

This is an important consideration because it can happen that bugs are introduced if the missing brackets are not noticed:
```js
if (chamonix_cable_car.is_ready())
    console.log('cable car is starting');
    chamonix_cable_car.start();
```

2020-10-02 07:42 UTC, pedroamarocern commented on src/ui/components/checklists/Checklists.js
> +            return <ChecklistSignature signature={signature}
Can remove the `{`/`}`/`return`, since it is a single statement.

2020-10-02 09:13 UTC, BoykoBorisov commented on src/ui/components/checklists/ChecklistSignature.js
> +          qualification: this.props.signature.responsibilityDescription,
Fixed

2020-10-02 09:13 UTC, BoykoBorisov commented on src/ui/components/checklists/ChecklistSignature.js
> +export default class ChecklistSignature extends Component{
Fixed.

2020-10-02 09:13 UTC, BoykoBorisov commented on src/ui/components/checklists/ChecklistSignature.js
> +    openDialogue = () =>{
Fixed.

2020-10-02 09:14 UTC, BoykoBorisov commented on src/ui/components/checklists/ChecklistSignature.js
> +       var signature = {workOrderCode: this.props.workOrderCode,
Agree, applied the suggested change.

2020-10-02 09:15 UTC, BoykoBorisov commented on src/ui/components/checklists/ChecklistSignature.js
> +        });
Agree, suggestion was applied.

2020-10-02 09:15 UTC, BoykoBorisov commented on src/ui/components/checklists/ChecklistSignature.js
> +                    <Grid item xs={2} md={2} lg={2}>
Fixed

2020-10-02 09:15 UTC, BoykoBorisov commented on src/ui/components/checklists/Checklists.js
> +            signaturesCollapsed: new Map()
Suggestion taken.

2020-10-02 09:16 UTC, BoykoBorisov commented on src/ui/components/checklists/Checklists.js
> +        this.setState(this.state.signaturesCollapsed.set(activity, !this.state.signaturesCollapsed.get(activity)));
Fixed bug by making setState use a deep copy of the Object.

2020-10-02 09:17 UTC, BoykoBorisov commented on src/ui/components/checklists/Checklists.js
> +          return;
Change made.

2020-10-02 09:17 UTC, BoykoBorisov commented on src/ui/components/checklists/Checklists.js
> +            return <ChecklistSignature signature={signature}
Change made.

2020-10-06 12:59 UTC, pedroamarocern reviewed
Minor changes, otherwise looks good to me!

2020-10-06 12:59 UTC, pedroamarocern commented on src/ui/components/checklists/fields/ChecklistFieldNumeric.js
> +    console.log(props);
Not needed.

2020-10-06 12:59 UTC, pedroamarocern commented on src/ui/components/checklists/ChecklistSignature.js
> +        });
```
.finally(() => {
     this.closeDialogue();
});
```
->
```
.finally(this.closeDialogue);
```

2020-10-06 13:26 UTC, pedroamarocern reviewed
Empty review.

2020-10-08 13:32 UTC, pedroamarocern reviewed
I believe that we should consider where to store the signature state to accommodate clearing all signatures.

2020-10-08 13:32 UTC, pedroamarocern commented on src/ui/components/checklists/ChecklistItem.js
> +                }).catch(error => {
Alternatively use `.then(this.props.resetSignatures.bind(null, checklistItem.activityCode))`, but this is completely fine.

2020-10-08 13:32 UTC, pedroamarocern commented on src/ui/components/checklists/Checklists.js
> +        })
Although the activities array itself is not mutated, each object inside the original activities is modified, as references to those objects are copied.

2020-10-08 13:32 UTC, pedroamarocern commented on src/ui/components/checklists/Checklists.js
> +            });
In `onUpdateChecklistItem` one can find `const activityIndex = activities.findIndex(activity => activity.activityCode === activityCode);`. Would this idea help here?

2020-10-08 13:32 UTC, pedroamarocern commented on src/ui/components/checklists/ChecklistSignature.js
> +    }
I think only keeping the state of who signed what and at what time in one place, the Checklists component, is the ideal solution here. Perhaps we should discuss this over Zoom?

2020-10-08 13:32 UTC, pedroamarocern commented on src/ui/components/checklists/ChecklistSignature.js
> +            this.props.setSignature(this.props.activityCode, this.props.signature.type, response.body.data.signer, response.body.data.timeStamp);
Looks good, setState moved to the upper component.

2020-10-08 14:52 UTC, pedroamarocern commented on src/ui/components/checklists/Checklists.js
> +            })
Note that activity.signatures is mutated in this case, as the array is modified in line 166 without being copied. Consider using `activity.signatures = activity.signatures.map(signature => ({...signature, signer: null, ...}))` to both fix the mutation and simplify the code.

2020-10-08 14:52 UTC, pedroamarocern commented on src/ui/components/checklists/Checklists.js
> +            const activityIndex = activities.findIndex = activities.findIndex(activity => activityCode === activity.activityCode);
`activities.findIndex =`?

2020-10-08 14:52 UTC, pedroamarocern commented on src/ui/components/checklists/Checklists.js
> +            activity.signatures[signatureIndex].time = time;
To remove the repetition of `activity.signatures[signatureIndex]` we can assign `{...activity.signatures[signatureIndex]}` to a variable.

2020-10-08 15:07 UTC, pedroamarocern reviewed
Missing https://github.com/cern-eam/eam-components/pull/52#discussion_r501779932 , rest looks ok!

2020-10-08 15:07 UTC, pedroamarocern commented on src/ui/components/checklists/Checklists.js
> +        console.log('reset');
`console.log`

2020-10-08 15:33 UTC, pedroamarocern reviewed
Looks good to me!

2020-10-08 15:33 UTC, pedroamarocern commented on src/ui/components/checklists/Checklists.js
> +                return signatureCopy;
Alternatively we can do `signature => ({...signature, signer: null, time: null})`.

2020-10-14 12:51 UTC, pedroamarocern requested changes

2020-10-14 12:51 UTC, pedroamarocern commented on src/ui/components/checklists/ChecklistSignature.js
> +          qualification: this.props.signature.responsibilityDescription,
Why is `this.props.signature.responsibilityDescription` in state if it does not change?

If this is not required, then the constructor can be removed and the state set as follows:
```js
export default class ChecklistSignature extends Component {
    state = {
        open: false,
        username: null,
        password: null
    }
    // ...
```

2020-10-14 12:51 UTC, pedroamarocern commented on src/ui/components/checklists/ChecklistSignature.js
> +                    {(this.props.signature.viewAsPerformer || this.props.signature.type === 'RB01') &&
To simplify getting the `this.props.signature`, we can use `const { signature } = this.props` at the very beginning of the `render()` function. This also helps if later we wish to retrieve the variable from somewhere else (such as `this.state`), as then we only have to change this mapping in one place.

2020-10-14 12:51 UTC, pedroamarocern commented on src/ui/components/checklists/Checklists.js
> +            }
I would keep the semicolon here in this case. Although both ways technically work, Javascript will automatically add a semicolon in certain cases, which does not always end up where one can expect.

For instance, Javascript will interpret
```js
a = b
(c + d).print()
```
as
```js
a = b(c + d).print()
```

2020-10-14 12:51 UTC, pedroamarocern commented on src/ui/components/checklists/Checklists.js
> +            const activityIndex = activities.findIndex(activity => activityCode === activity.activityCode)
For the reason above also suggest using `;` here and in activity.signatures below.

2020-10-14 12:51 UTC, pedroamarocern commented on src/ui/components/checklists/Checklists.js
> +    }
Is it not possible to simplify `resetSignatures` by calling `setSignature` 3 times at most?

2020-10-14 12:51 UTC, pedroamarocern commented on src/ui/components/checklists/Checklists.js
> +            activity.signatures[signatureIndex] = {...activity.signatures[signatureIndex]};
I believe `activity.signatures` is mutated here.

2020-10-14 12:51 UTC, pedroamarocern commented on src/ui/components/checklists/Checklists.js
> +    renderSignatures(activity){
`expandSignature(activity){` => `expandSignature = (activity) => {`

This is crucial to being able to use this as an event handler for a component: `onChange={this.expandSignature}`

2020-10-14 12:51 UTC, pedroamarocern commented on src/ui/components/checklists/Checklists.js
> +                                                onChange={(_, expanded) => this.expandSignature(activity)}>
Why is `expanded` ignored? Although practically this works, what if the function here is theoretically called twice with the same value of `expanded`?

2020-10-14 12:51 UTC, pedroamarocern commented on src/ui/components/checklists/Checklists.js
> +                                                expanded={!this.state.signaturesCollapsed[activity.activityCode]}
Nitpick: consider renaming signaturesCollapsed to signaturesExpanded to avoid the inversion here.

2020-10-14 12:51 UTC, pedroamarocern commented on src/ui/components/checklists/Checklists.js
> +                            <ExpansionPanelDetails style={{margin: 0, padding: '0 24px 0 24px', backgroundColor: 'white', minHeight: '50px'}}>
`0 24px 0 24px` can be rewritten as `0 24px`, as if there are only 2 values, the first one will be used for the top/bottom padding and the second for the left/right padding.

2020-10-14 12:51 UTC, pedroamarocern commented on src/ui/components/checklists/fields/ChecklistFieldNumeric.js
> +    console.log(props);
☝️

2020-10-14 12:51 UTC, pedroamarocern commented on src/ui/components/checklists/ChecklistSignature.js
> +    render(){
Nitpick: render() {

2020-10-14 12:51 UTC, pedroamarocern commented on src/ui/components/checklists/ChecklistSignature.js
> +    }
Instead of calling `signatureTypeSwitch(...)` we can directly specify `signatureTypes[...]`, which is even shorter.

2020-10-14 15:49 UTC, BoykoBorisov commented on src/ui/components/checklists/Checklists.js
> +                                                expanded={!this.state.signaturesCollapsed[activity.activityCode]}
I am doing this as the value is undefined initially.

2020-10-14 16:23 UTC, pedroamarocern approved these changes
Looks good to me!

2020-10-15 06:36 UTC, merged